name: PR Gate

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  backend-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm test -- --testPathIgnorePatterns=pact

  frontend-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false --coverage --testPathIgnorePatterns=pact

  contract-tests:
    name: Pact Contract Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run consumer tests (frontend)
        working-directory: ./frontend
        run: npm run test:pact

      - name: Run provider tests (backend)
        working-directory: ./backend
        run: npm run test:pact

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start servers and wait for readiness
        run: |
          # Start backend server
          cd backend
          nohup npm start > backend.log 2>&1 &
          BACKEND_PID=$!
          echo "Backend PID: $BACKEND_PID"
          sleep 2
          cd ..

          # Start frontend server
          cd frontend
          nohup npx serve -s build -l 3000 > frontend.log 2>&1 &
          FRONTEND_PID=$!
          echo "Frontend PID: $FRONTEND_PID"
          sleep 2
          cd ..

          # Check if processes are still running
          ps aux | grep $BACKEND_PID || echo "Backend process not found"
          ps aux | grep $FRONTEND_PID || echo "Frontend process not found"

          # Check logs before waiting
          echo "=== Backend log ==="
          cat backend/backend.log || echo "No backend log yet"
          echo "=== Frontend log ==="
          cat frontend/frontend.log || echo "No frontend log yet"

          # Wait for servers to be ready
          npx wait-on http://localhost:3001/health http://localhost:3000 --timeout 60000
        env:
          NODE_ENV: test

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
